### PR TITLE
Switch to using nbclassic NotebookApp

### PR DESCRIPTION
**Pull request by linuxrider**
With this change it is possible to run the appmode with nbclassic.
It reuses `NotebookApp` from nbclassic with minimal changes.

### CODE REVIEW

**Comment by oschuett** [comment]
This is awesome. Great work!

**Comment by danielhollas** [comment]
@linuxrider cool work. Just for me to understand, does appmode still support notebook after this change?

**Comment by linuxrider** [comment]
@danielhollas As far as I understand appmode stopped  working at least for notebook >= 7. With this change it will not work for notebook < 7 anymore. It will now work with nbclassic, independent of notebook being installed or not.

**Comment by danielhollas** [comment]
Oh, that is good to know. Would it be hard to support both?

@oschuett just checking if this was indeed an intention? In AiiDAlab we currently still on notebook<7.0. Our plan was to upgrade to notebook==7.0 when possible, but I guess now I am not sure what is the direction here.

**Comment by linuxrider** [comment]
I don't know how hard it would be to make it work for both nbclassic and notebook.
Since my impression was that it only worked for the classic notebook (< 7), I thought the right step was to base on nbclassic which is the replacement.

By the way, I updated it to use it with AiiDAlab.

**Comment by danielhollas** [comment]
Thank you for the info and implementation, that makes sense. 

My fear is that at least according to original plans laid in [JEP 79](https://jupyter.org/enhancement-proposals/79-notebook-v7/notebook-v7.html#timeline), `nbclassic` is not supposed to be maintained for very long. So in the future we will need to figure out how to migrate to Notebook 7 anyway, although how far of that is I don't know.

> By the way, I updated it to use it with AiiDAlab.

Oh cool! If you run into any issues when using nbclassic or anything else, please feel free to open issues or even PRs, e.g here https://github.com/aiidalab/aiidalab or https://github.com/aiidalab/aiidalab-docker-stack. It would help us a lot as we move in this direction.

**Comment by linuxrider** [comment]
> Thank you for the info and implementation, that makes sense.
> 
> My fear is that at least according to original plans laid in [JEP 79](https://jupyter.org/enhancement-proposals/79-notebook-v7/notebook-v7.html#timeline), `nbclassic` is not supposed to be maintained for very long. So in the future we will need to figure out how to migrate to Notebook 7 anyway, although how far of that is I don't know.

True. Maybe I find time to have a look.

**Comment by linuxrider** [comment]
I forgot to mention `appmode-jupyterlab`. I updated it so it should work with jupyterlab 4.
You find the changes here https://github.com/osscar-org/appmode-jupyterlab/pull/2

**Comment by danielhollas** [comment]
The new release will drop notebook support for notebook~=6.x if I understand correctly the above discussion, so we will not be able to use it straightaway in the current AiiDAlab docker images. But we're pinning the appmode version so I guess it's fine.

Cc @unkcpz

**Comment by oschuett** [comment]
Yes, this PR is the only significant change [since the last release](https://github.com/oschuett/appmode/compare/v0.9.0...master). So, you can just pin v0.9.0 for the time being.

One thing that is puzzling me now is the [binder/environment.yml](https://github.com/oschuett/appmode/blob/master/binder/environment.yml). Shouldn't the [setup.py](https://github.com/oschuett/appmode/blob/master/setup.py) be sufficient to install all requirements?

**Comment by linuxrider** [comment]
> Yes, this PR is the only significant change [since the last release](https://github.com/oschuett/appmode/compare/v0.9.0...master). So, you can just pin v0.9.0 for the time being.
> 
> One thing that is puzzling me now is the [binder/environment.yml](https://github.com/oschuett/appmode/blob/master/binder/environment.yml). Shouldn't the [setup.py](https://github.com/oschuett/appmode/blob/master/setup.py) be sufficient to install all requirements?

I would expect the setup.py to be enough. As far as I remember I took it from template I generated from the copier template at https://github.com/jupyterlab/extension-template

I' m not finished integrating it with the existing appmode.

**Comment by giovannipizzi** [comment]
Hi all! Thanks! I pinged @dou-du who merged osscar-org/appmode-jupyterlab#2 and will make a release soon.
@danielhollas maybe we should discuss this in the next AiiDAlab meeting, can you remember to discuss it?

**Comment by oschuett** [comment]
Hi Giovanni, It's great that https://github.com/osscar-org/appmode-jupyterlab/pull/2 got merged after all. I actually wouldn't mind to keep `appmode` and `appmode-jupyterlab` as two separate projects since they have almost no code in common. In any case, I'm happy to support whatever solution you decide on.

**Pull request merged**
